// Code generated by protoc-gen-go.
// source: service.proto
// DO NOT EDIT!

/*
Package service is a generated protocol buffer package.

It is generated from these files:
	service.proto

It has these top-level messages:
*/
package service

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import user "github.com/astaluego/test-grpc/server/pkg/protobuf/user"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for Route service

type RouteClient interface {
	New(ctx context.Context, in *user.User, opts ...grpc.CallOption) (*user.Response, error)
	Edit(ctx context.Context, in *user.User, opts ...grpc.CallOption) (*user.Response, error)
	Delete(ctx context.Context, in *user.User, opts ...grpc.CallOption) (*user.Response, error)
	List(ctx context.Context, in *user.User, opts ...grpc.CallOption) (*user.Response, error)
}

type routeClient struct {
	cc *grpc.ClientConn
}

func NewRouteClient(cc *grpc.ClientConn) RouteClient {
	return &routeClient{cc}
}

func (c *routeClient) New(ctx context.Context, in *user.User, opts ...grpc.CallOption) (*user.Response, error) {
	out := new(user.Response)
	err := grpc.Invoke(ctx, "/Route/New", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *routeClient) Edit(ctx context.Context, in *user.User, opts ...grpc.CallOption) (*user.Response, error) {
	out := new(user.Response)
	err := grpc.Invoke(ctx, "/Route/Edit", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *routeClient) Delete(ctx context.Context, in *user.User, opts ...grpc.CallOption) (*user.Response, error) {
	out := new(user.Response)
	err := grpc.Invoke(ctx, "/Route/Delete", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *routeClient) List(ctx context.Context, in *user.User, opts ...grpc.CallOption) (*user.Response, error) {
	out := new(user.Response)
	err := grpc.Invoke(ctx, "/Route/List", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Route service

type RouteServer interface {
	New(context.Context, *user.User) (*user.Response, error)
	Edit(context.Context, *user.User) (*user.Response, error)
	Delete(context.Context, *user.User) (*user.Response, error)
	List(context.Context, *user.User) (*user.Response, error)
}

func RegisterRouteServer(s *grpc.Server, srv RouteServer) {
	s.RegisterService(&_Route_serviceDesc, srv)
}

func _Route_New_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(user.User)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RouteServer).New(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Route/New",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RouteServer).New(ctx, req.(*user.User))
	}
	return interceptor(ctx, in, info, handler)
}

func _Route_Edit_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(user.User)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RouteServer).Edit(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Route/Edit",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RouteServer).Edit(ctx, req.(*user.User))
	}
	return interceptor(ctx, in, info, handler)
}

func _Route_Delete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(user.User)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RouteServer).Delete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Route/Delete",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RouteServer).Delete(ctx, req.(*user.User))
	}
	return interceptor(ctx, in, info, handler)
}

func _Route_List_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(user.User)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RouteServer).List(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Route/List",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RouteServer).List(ctx, req.(*user.User))
	}
	return interceptor(ctx, in, info, handler)
}

var _Route_serviceDesc = grpc.ServiceDesc{
	ServiceName: "Route",
	HandlerType: (*RouteServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "New",
			Handler:    _Route_New_Handler,
		},
		{
			MethodName: "Edit",
			Handler:    _Route_Edit_Handler,
		},
		{
			MethodName: "Delete",
			Handler:    _Route_Delete_Handler,
		},
		{
			MethodName: "List",
			Handler:    _Route_List_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "service.proto",
}

func init() { proto.RegisterFile("service.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 117 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xe2, 0xe2, 0x2d, 0x4e, 0x2d, 0x2a,
	0xcb, 0x4c, 0x4e, 0xd5, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x97, 0xe2, 0x2f, 0x2d, 0x4e, 0x2d, 0xd2,
	0x07, 0x11, 0x10, 0x01, 0xa3, 0x0a, 0x2e, 0xd6, 0xa0, 0xfc, 0xd2, 0x92, 0x54, 0x21, 0x49, 0x2e,
	0x66, 0xbf, 0xd4, 0x72, 0x21, 0x56, 0xbd, 0xd0, 0xe2, 0xd4, 0x22, 0x29, 0x4e, 0xbd, 0xa0, 0xd4,
	0xe2, 0x82, 0xfc, 0xbc, 0xe2, 0x54, 0x25, 0x06, 0x21, 0x29, 0x2e, 0x16, 0xd7, 0x94, 0xcc, 0x12,
	0xac, 0x72, 0x32, 0x5c, 0x6c, 0x2e, 0xa9, 0x39, 0xa9, 0x25, 0xa9, 0xb8, 0x74, 0xfa, 0x64, 0x16,
	0x63, 0xd5, 0x99, 0xc4, 0x06, 0x76, 0x80, 0x31, 0x20, 0x00, 0x00, 0xff, 0xff, 0x45, 0x74, 0x92,
	0xc3, 0xa2, 0x00, 0x00, 0x00,
}
